name: "Pull Request Label Reviewers"
on:
  pull_request_target:
    types:
      - unlabeled
      - labeled

jobs:
  assign_and_unassign:
    permissions:
      pull-requests: write
    name: assign and unassign reviewers
    runs-on: ubuntu-latest
    steps:
      - name: main
        id: assign-reviewers
        uses: totallymoney/assign-reviewers-by-labels-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
