name: "Pull Request Reviewers by Label"
on:
  workflow_call:
  pull_request_target:
    types:
      - unlabeled
      - labeled

jobs:
  assign_and_unassign:
    permissions:
      pull-requests: write
    name: assign and unassign reviewers
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers
        id: assign-reviewers
        uses: totallymoney/assign-reviewers-by-labels-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
