name: "Copy labels from referenced issue"
on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  #copy-labels:
  #  permissions:
  #    issues: read
  #    pull-requests: write
  #  runs-on: ubuntu-latest
  #  name: Copy labels from referenced issue
  #  steps:
  #    - name: Copy labels
  #      id: copy-labels
  #      uses: michalvankodev/copy-issue-labels@v1.3.0
  #      with:
  #        repo-token: ${{ secrets.PR_LABELS_TOKEN }}
  add-assignee:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Add assignee to the PR
    steps:
      - name: Add assignee to the PR
        id: add-assignee
        # if: ${{ github.event.pull_request.assignees == null || github.event.pull_request.assignees == '' }}
        run: echo ${{ github.event }} | jq
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  check-issue-linked:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    name: Check issue linked to PR
    steps:
      - name: Get linked issues
        id: get-linked-issues
        run: |
          QUERY='{
                    repository(owner:"${OWNER}", name:"${REPO}") {
                      pullRequest(number: ${PR_ID}) {
                        closingIssuesReferences(first: 10) {
                          totalCount
                        }
                      }
                    }
                  }'
          ISSUE_COUNT=$(gh api graphql -f query="$QUERY" --jq '.data.repository.pullRequest.closingIssuesReferences.totalCount')
          echo "issue_count=$ISSUE_COUNT" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository.name }}
          OWNER: ${{ github.repository_owner }}
          PR_ID: ${{ github.event.pull_request.number }}
      - name: Fail if no issue
        id: fail-if-no-issue
        if: env.issue_count == '0'
        run: echo "No linked issues found. Please link an issue to this PR" && exit 1
